# Generated by Django 4.0.5 on 2022-07-08 14:07

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_matches_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='match_id',
            field=models.ForeignKey(db_column=builtins.id, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.matches'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
